
apiVersion: v1
kind: Namespace
metadata:
  name: otel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-hello
  template:
    metadata:
      labels:
        app: otel-hello
    spec:
      containers:
      - name: otel-hello
        image: quay.io/husky_parul/otel_hello:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2223
          name: http
        env:
        - name: "EXPORTER_TYPE"
          value: "prometheus"
---
apiVersion: v1
kind: Service
metadata:
  name: otel-hello-service
spec:
  selector:
    app: otel-hello
  ports:
    - name: http
      protocol: TCP
      port: 2223
      targetPort: http