receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318 
      grpc:
        endpoint: localhost:4317
processors: {}
exporters:
  logging:
    verbosity: detailed
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging]
      processors: []